version: 2
updates:
  # GitHub actions
-   package-ecosystem: github-actions
    directory: /    # For GitHub Actions "/" must be used for workflow files in ".github/workflows"
    schedule:
        interval: monthly
    commit-message:
        prefix: 'chore: '
    labels:
    -   release/patch

  # Terraform
-   package-ecosystem: terraform
    directory: /
    schedule:
        interval: monthly
    commit-message:
        prefix: 'chore: '
    labels:
    -   release/patch

-   package-ecosystem: terraform
    directory: /examples/lambda/
    schedule:
        interval: monthly
    commit-message:
        prefix: 'chore: '
    labels:
    -   release/patch
